remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Plank Reloaded
description: A simple and elegant dock for X11 desktop environments.
url: https://plankreloaded.org
logo: data/icons/128x128/plank-reloaded.png
show_downloads: true